import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Shield, CheckCircle, Clock, AlertCircle, Eye, Download } from "lucide-react";

const Proofs = () => {
  const proofs = [
    {
      id: "zk_proof_001",
      title: "Image Recognition Proof",
      description: "Zero-knowledge proof for image classification accuracy",
      status: "verified",
      confidence: 98.5,
      timestamp: "2024-01-15T14:30:00Z",
      verifier: "0x742d35Cc6634C0532925a3b8D43EC6d1",
      size: "2.4 KB"
    },
    {
      id: "zk_proof_002", 
      title: "Search Query Validation",
      description: "Proof of search result authenticity and ranking algorithm",
      status: "pending",
      confidence: 95.2,
      timestamp: "2024-01-15T14:15:00Z",
      verifier: "0x8ba1f109551bD432803012645Hac136c",
      size: "3.1 KB"
    },
    {
      id: "zk_proof_003",
      title: "Indexer Computation Proof",
      description: "Validation of indexer node computational work and results",
      status: "verified",
      confidence: 99.1,
      timestamp: "2024-01-15T13:45:00Z",
      verifier: "0x1aE0EA34a72D944a8C7603FfB3eC30a6",
      size: "1.8 KB"
    },
    {
      id: "zk_proof_004",
      title: "Consensus Mechanism Proof",
      description: "Zero-knowledge proof of consensus algorithm correctness",
      status: "failed",
      confidence: 67.3,
      timestamp: "2024-01-15T13:20:00Z",
      verifier: "0x5aAeb6053F3E94C9b9A09f33669435E7",
      size: "2.9 KB"
    }
  ];

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "verified":
        return <CheckCircle className="w-5 h-5 text-green-400" />;
      case "pending":
        return <Clock className="w-5 h-5 text-yellow-400" />;
      case "failed":
        return <AlertCircle className="w-5 h-5 text-red-400" />;
      default:
        return <Shield className="w-5 h-5 text-muted-foreground" />;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "verified":
        return "bg-green-500/20 text-green-400 border-green-500/30";
      case "pending":
        return "bg-yellow-500/20 text-yellow-400 border-yellow-500/30";
      case "failed":
        return "bg-red-500/20 text-red-400 border-red-500/30";
      default:
        return "bg-muted/20 text-muted-foreground border-muted/30";
    }
  };

  return (
    <div className="container mx-auto px-6 py-8">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold mb-4">ZK Proofs Dashboard</h1>
          <p className="text-lg text-muted-foreground">
            View and verify zero-knowledge proofs generated by the network
          </p>
        </div>

        {/* Stats Overview */}
        <div className="grid md:grid-cols-4 gap-6 mb-8">
          <Card className="glass-card p-6 text-center">
            <div className="w-12 h-12 bg-green-500/20 rounded-lg flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-6 h-6 text-green-400" />
            </div>
            <div className="text-2xl font-bold text-green-400">1,247</div>
            <div className="text-sm text-muted-foreground">Verified Proofs</div>
          </Card>
          
          <Card className="glass-card p-6 text-center">
            <div className="w-12 h-12 bg-yellow-500/20 rounded-lg flex items-center justify-center mx-auto mb-4">
              <Clock className="w-6 h-6 text-yellow-400" />
            </div>
            <div className="text-2xl font-bold text-yellow-400">23</div>
            <div className="text-sm text-muted-foreground">Pending</div>
          </Card>
          
          <Card className="glass-card p-6 text-center">
            <div className="w-12 h-12 bg-primary/20 rounded-lg flex items-center justify-center mx-auto mb-4">
              <Shield className="w-6 h-6 text-primary" />
            </div>
            <div className="text-2xl font-bold">96.8%</div>
            <div className="text-sm text-muted-foreground">Success Rate</div>
          </Card>
          
          <Card className="glass-card p-6 text-center">
            <div className="w-12 h-12 bg-purple-500/20 rounded-lg flex items-center justify-center mx-auto mb-4">
              <Download className="w-6 h-6 text-purple-400" />
            </div>
            <div className="text-2xl font-bold">2.3 MB</div>
            <div className="text-sm text-muted-foreground">Total Size</div>
          </Card>
        </div>

        {/* Proofs List */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold">Recent Proofs</h2>
            <Button className="hero-button">
              <Shield className="w-4 h-4 mr-2" />
              Generate New Proof
            </Button>
          </div>

          {proofs.map((proof) => (
            <Card key={proof.id} className="glass-card p-6 hover:shadow-elegant transition-all duration-300">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    {getStatusIcon(proof.status)}
                    <h3 className="text-xl font-semibold">{proof.title}</h3>
                    <Badge className={`border ${getStatusColor(proof.status)}`}>
                      {proof.status}
                    </Badge>
                  </div>
                  
                  <p className="text-muted-foreground mb-4">{proof.description}</p>
                  
                  <div className="grid md:grid-cols-4 gap-4 text-sm">
                    <div>
                      <span className="text-muted-foreground">Proof ID:</span>
                      <div className="font-mono text-primary">{proof.id}</div>
                    </div>
                    
                    <div>
                      <span className="text-muted-foreground">Confidence:</span>
                      <div className="font-semibold">{proof.confidence}%</div>
                    </div>
                    
                    <div>
                      <span className="text-muted-foreground">Verifier:</span>
                      <div className="font-mono text-xs">{proof.verifier}</div>
                    </div>
                    
                    <div>
                      <span className="text-muted-foreground">Size:</span>
                      <div className="font-semibold">{proof.size}</div>
                    </div>
                  </div>
                  
                  <div className="mt-4 text-xs text-muted-foreground">
                    Generated: {new Date(proof.timestamp).toLocaleString()}
                  </div>
                </div>
                
                <div className="flex flex-col space-y-2 ml-6">
                  <Button variant="outline" size="sm" className="glass-card">
                    <Eye className="w-4 h-4 mr-2" />
                    View
                  </Button>
                  <Button variant="outline" size="sm" className="glass-card">
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Proofs;